/**
 * Generate `src/plugins/katex-css.generated.ts` from the installed KaTeX stylesheet.
 *
 * `MathPlugin` injects KaTeX's CSS into the document as a `<style>` element, so it needs
 * the stylesheet as a JavaScript string. The obvious ways to get one are both
 * bundler-specific: Vite's `?raw` suffix leaves an unresolvable specifier in the published
 * `dist/`, and a bare `.css` import depends on the consuming bundler treating CSS as text
 * — which `apps/web` (Next.js) does not, since it imports `src/` directly.
 *
 * Emitting a plain TypeScript module sidesteps both. Every consumer, on either entry
 * point, sees an ordinary string constant.
 *
 * The output is committed so that a fresh clone and the `./src` export work without a
 * build step. Re-run after bumping `katex`.
 *
 * @example
 * ```sh
 * bun run generate:katex-css
 * ```
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const source = join(here, "..", "node_modules", "katex", "dist", "katex.min.css");
const target = join(here, "..", "src", "plugins", "katex-css.generated.ts");

const css = readFileSync(source, "utf8").trim();
const version = JSON.parse(readFileSync(join(here, "..", "node_modules", "katex", "package.json"), "utf8"))
  .version as string;

const banner = `/**
 * KaTeX ${version}'s stylesheet, as a string.
 *
 * Generated by \`scripts/generate-katex-css.ts\` — do not edit by hand. Re-run
 * \`bun run generate:katex-css\` after bumping the \`katex\` dependency.
 *
 * Note that the \`@font-face\` rules reference \`fonts/KaTeX_*\` relatively. Injected into a
 * document, they resolve against the page URL rather than the package, so a consumer who
 * wants KaTeX's own fonts must still serve them.
 */
export const katexCss = ${JSON.stringify(css)};
`;

writeFileSync(target, banner, "utf8");
console.log(`Wrote ${target} (${(css.length / 1024).toFixed(1)} KB from katex ${version})`);
