/**
 * Generate `src/plugins/katex-styles.generated.ts` from the installed KaTeX stylesheet.
 *
 * Two problems are solved here at once.
 *
 * **Getting the CSS as a string.** `MathPlugin` injects KaTeX's stylesheet as a `<style>`
 * element, so it needs one. The obvious ways are both bundler-specific: Vite's `?raw`
 * suffix leaves an unresolvable specifier in the published `dist/`, and a bare `.css`
 * import depends on the consuming bundler treating CSS as text — which `apps/web`
 * (Next.js) does not, since it imports `src/` directly. A plain TypeScript module
 * sidesteps both.
 *
 * **Getting the fonts to load.** KaTeX's `@font-face` rules reference `fonts/KaTeX_*`
 * *relatively*, so a `<style>` element resolves them against the consumer's page URL and
 * they 404 — the defect behind open question 17. Every `src` is therefore rewritten to a
 * `data:` URI here, which resolves the same everywhere.
 *
 * Only the `.woff2` sources survive. KaTeX lists woff2, woff and ttf for each face;
 * inlining all three would triple the payload for browsers that have supported woff2
 * since 2016. Dropping the fallbacks keeps the module near 400 KB rather than 1.6 MB.
 *
 * The output is committed so that a fresh clone and the `./src` export work without a
 * build step. Re-run after bumping `katex`.
 *
 * @example
 * ```sh
 * bun run generate:katex-styles
 * ```
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const katexDir = join(here, "..", "node_modules", "katex");
const source = join(katexDir, "dist", "katex.min.css");
const target = join(here, "..", "src", "plugins", "katex-styles.generated.ts");

const version = JSON.parse(readFileSync(join(katexDir, "package.json"), "utf8")).version as string;

/**
 * Read one font file and return it as a `data:` URI.
 *
 * @param file - Path relative to `katex/dist`, as it appears in the stylesheet
 * @returns A base64 `data:font/woff2` URI
 */
function inlineFont(file: string): string {
  const bytes = readFileSync(join(katexDir, "dist", file));
  return `data:font/woff2;base64,${bytes.toString("base64")}`;
}

/**
 * Rewrite one `@font-face` rule's `src` list down to a single inlined woff2 source.
 *
 * KaTeX's minified rules read
 * `src:url(fonts/X.woff2) format("woff2"),url(fonts/X.woff) format("woff"),...`.
 * Anything that is not a woff2 reference is dropped rather than inlined.
 *
 * @param srcList - The matched `src:...` declaration, without its terminator
 * @returns A replacement declaration carrying one `data:` URI
 */
function inlineSrcList(srcList: string): string {
  const woff2 = /url\((fonts\/[\w-]+\.woff2)\)/.exec(srcList);
  if (!woff2?.[1]) return srcList;
  return `src:url(${inlineFont(woff2[1])}) format("woff2")`;
}

const raw = readFileSync(source, "utf8").trim();
const css = raw.replace(/src:url\(fonts\/[^;}]*/g, (match) => inlineSrcList(match));

const survivor = /url\(fonts\//.exec(css);
if (survivor) {
  throw new Error(`A relative font URL survived rewriting: ${css.slice(survivor.index, survivor.index + 60)}`);
}

const banner = `/**
 * KaTeX ${version}'s stylesheet, with every font inlined as a \`data:\` URI.
 *
 * Generated by \`scripts/generate-katex-styles.ts\` — do not edit by hand. Re-run
 * \`bun run generate:katex-styles\` after bumping the \`katex\` dependency.
 *
 * This module is large (~${(css.length / 1024).toFixed(0)} KB) and is reached only through a dynamic \`import()\` in
 * \`math-plugin.ts\`, so a consumer who leaves \`MathPluginOptions.injectStyles\` at its
 * default of \`false\` never pays for it. Do not import it statically.
 */
export const katexStyles = ${JSON.stringify(css)};
`;

writeFileSync(target, banner, "utf8");
console.log(`Wrote ${target} (${(css.length / 1024).toFixed(1)} KB from katex ${version})`);
